//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"管培生_提资标准_录入")]
    public partial class ManagementTraineePayRiseStandardInput : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f届别;
        [Size(10)]
        [WatchMember]
        public string 届别
        {
            get { return f届别; }
            set { SetPropertyValue<string>("届别", ref f届别, value); }
        }
        string f岗位级别;
        [Size(10)]
        [WatchMember]
        public string 岗位级别
        {
            get { return f岗位级别; }
            set { SetPropertyValue<string>("岗位级别", ref f岗位级别, value); }
        }
        string f类别;
        [Size(20)]
        [WatchMember]
        public string 类别
        {
            get { return f类别; }
            set { SetPropertyValue<string>("类别", ref f类别, value); }
        }
        int f序号;
        public int 序号
        {
            get { return f序号; }
            set { SetPropertyValue<int>("序号", ref f序号, value); }
        }
        decimal f一阶起薪;
        [WatchMember]
        public decimal 一阶起薪
        {
            get { return f一阶起薪; }
            set { SetPropertyValue<decimal>("一阶起薪", ref f一阶起薪, value); }
        }
        decimal f二阶起薪;
        [WatchMember]
        public decimal 二阶起薪
        {
            get { return f二阶起薪; }
            set { SetPropertyValue<decimal>("二阶起薪", ref f二阶起薪, value); }
        }
        decimal f满阶A起薪;
        [WatchMember]
        public decimal 满阶A起薪
        {
            get { return f满阶A起薪; }
            set { SetPropertyValue<decimal>("满阶A起薪", ref f满阶A起薪, value); }
        }
        decimal f满阶B起薪;
        [WatchMember]
        public decimal 满阶B起薪
        {
            get { return f满阶B起薪; }
            set { SetPropertyValue<decimal>("满阶B起薪", ref f满阶B起薪, value); }
        }
        decimal f满阶C起薪;
        [WatchMember]
        public decimal 满阶C起薪
        {
            get { return f满阶C起薪; }
            set { SetPropertyValue<decimal>("满阶C起薪", ref f满阶C起薪, value); }
        }
        int f一阶起薪方式;
        public int 一阶起薪方式
        {
            get { return f一阶起薪方式; }
            set { SetPropertyValue<int>("一阶起薪方式", ref f一阶起薪方式, value); }
        }
        int f二阶起薪方式;
        public int 二阶起薪方式
        {
            get { return f二阶起薪方式; }
            set { SetPropertyValue<int>("二阶起薪方式", ref f二阶起薪方式, value); }
        }
        int f满阶起薪方式;
        public int 满阶起薪方式
        {
            get { return f满阶起薪方式; }
            set { SetPropertyValue<int>("满阶起薪方式", ref f满阶起薪方式, value); }
        }

        decimal f一阶增幅1;
        [WatchMember]
        public decimal 一阶增幅1
        {
            get { return f一阶增幅1; }
            set { SetPropertyValue<decimal>("一阶增幅1", ref f一阶增幅1, value); }
        }
        decimal f一阶增幅2;
        [WatchMember]
        public decimal 一阶增幅2
        {
            get { return f一阶增幅2; }
            set { SetPropertyValue<decimal>("一阶增幅2", ref f一阶增幅2, value); }
        }
        decimal f一阶增幅3;
        [WatchMember]
        public decimal 一阶增幅3
        {
            get { return f一阶增幅3; }
            set { SetPropertyValue<decimal>("一阶增幅3", ref f一阶增幅3, value); }
        }
        decimal f一阶增幅4;
        [WatchMember]
        public decimal 一阶增幅4
        {
            get { return f一阶增幅4; }
            set { SetPropertyValue<decimal>("一阶增幅4", ref f一阶增幅4, value); }
        }
        decimal f一阶增幅5;
        [WatchMember]
        public decimal 一阶增幅5
        {
            get { return f一阶增幅5; }
            set { SetPropertyValue<decimal>("一阶增幅5", ref f一阶增幅5, value); }
        }
        decimal f一阶增幅6;
        [WatchMember]
        public decimal 一阶增幅6
        {
            get { return f一阶增幅6; }
            set { SetPropertyValue<decimal>("一阶增幅6", ref f一阶增幅6, value); }
        }
        decimal f一阶增幅7;
        [WatchMember]
        public decimal 一阶增幅7
        {
            get { return f一阶增幅7; }
            set { SetPropertyValue<decimal>("一阶增幅7", ref f一阶增幅7, value); }
        }
        decimal f一阶增幅8;
        [WatchMember]
        public decimal 一阶增幅8
        {
            get { return f一阶增幅8; }
            set { SetPropertyValue<decimal>("一阶增幅8", ref f一阶增幅8, value); }
        }
        decimal f一阶增幅9;
        [WatchMember]
        public decimal 一阶增幅9
        {
            get { return f一阶增幅9; }
            set { SetPropertyValue<decimal>("一阶增幅9", ref f一阶增幅9, value); }
        }
        decimal f一阶增幅10;
        [WatchMember]
        public decimal 一阶增幅10
        {
            get { return f一阶增幅10; }
            set { SetPropertyValue<decimal>("一阶增幅10", ref f一阶增幅10, value); }
        }
        decimal f一阶增幅11;
        [WatchMember]
        public decimal 一阶增幅11
        {
            get { return f一阶增幅11; }
            set { SetPropertyValue<decimal>("一阶增幅11", ref f一阶增幅11, value); }
        }
        decimal f一阶增幅12;
        [WatchMember]
        public decimal 一阶增幅12
        {
            get { return f一阶增幅12; }
            set { SetPropertyValue<decimal>("一阶增幅12", ref f一阶增幅12, value); }
        }

        decimal f二阶增幅1;
        [WatchMember]
        public decimal 二阶增幅1
        {
            get { return f二阶增幅1; }
            set { SetPropertyValue<decimal>("二阶增幅1", ref f二阶增幅1, value); }
        }
        decimal f二阶增幅2;
        [WatchMember]
        public decimal 二阶增幅2
        {
            get { return f二阶增幅2; }
            set { SetPropertyValue<decimal>("二阶增幅2", ref f二阶增幅2, value); }
        }
        decimal f二阶增幅3;
        [WatchMember]
        public decimal 二阶增幅3
        {
            get { return f二阶增幅3; }
            set { SetPropertyValue<decimal>("二阶增幅3", ref f二阶增幅3, value); }
        }
        decimal f二阶增幅4;
        [WatchMember]
        public decimal 二阶增幅4
        {
            get { return f二阶增幅4; }
            set { SetPropertyValue<decimal>("二阶增幅4", ref f二阶增幅4, value); }
        }
        decimal f二阶增幅5;
        [WatchMember]
        public decimal 二阶增幅5
        {
            get { return f二阶增幅5; }
            set { SetPropertyValue<decimal>("二阶增幅5", ref f二阶增幅5, value); }
        }
        decimal f二阶增幅6;
        [WatchMember]
        public decimal 二阶增幅6
        {
            get { return f二阶增幅6; }
            set { SetPropertyValue<decimal>("二阶增幅6", ref f二阶增幅6, value); }
        }

        string f创建人;
        [Size(20)]
        public string 创建人
        {
            get { return f创建人; }
            set { SetPropertyValue<string>("创建人", ref f创建人, value); }
        }
        string f录入人;
        [Size(20)]
        public string 录入人
        {
            get { return f录入人; }
            set { SetPropertyValue<string>("录入人", ref f录入人, value); }
        }
        DateTime f录入时间;
        public DateTime 录入时间
        {
            get { return f录入时间; }
            set { SetPropertyValue<DateTime>("录入时间", ref f录入时间, value); }
        }
        bool f是验证录入;
        public bool 是验证录入
        {
            get { return f是验证录入; }
            set { SetPropertyValue<bool>("是验证录入", ref f是验证录入, value); }
        }
        DateTime f生效时间;
        public DateTime 生效时间
        {
            get { return f生效时间; }
            set { SetPropertyValue<DateTime>("生效时间", ref f生效时间, value); }
        }
        public ManagementTraineePayRiseStandardInput() : base(MyHelper.XpoSession) { }
        public ManagementTraineePayRiseStandardInput(Session session) : base(session) { }
    }

}
