//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"会员_部门排序")]
    public partial class DeptIndex : XPLiteObject
    {
        string f部门编号;
        [Key]
        [Size(10)]
        public string 部门编号
        {
            get { return f部门编号; }
            set { SetPropertyValue<string>("部门编号", ref f部门编号, value); }
        }
        string f公司名称;
        [Size(20)]
        public string 公司名称
        {
            get { return f公司名称; }
            set { SetPropertyValue<string>("公司名称", ref f公司名称, value); }
        }
        int f序号;
        public int 序号
        {
            get { return f序号; }
            set { SetPropertyValue<int>("序号", ref f序号, value); }
        }
    }

}
