//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"薪酬结构_报账工资_发放明细")]
    public partial class MonthlyRembursementSalaryItem : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f员工编号;
        [Size(20)]
        [WatchMember]
        public string 员工编号
        {
            get { return f员工编号; }
            set { SetPropertyValue<string>("员工编号", ref f员工编号, value); }
        }
        string f姓名;
        [Size(20)]
        [WatchMember]
        public string 姓名
        {
            get { return f姓名; }
            set { SetPropertyValue<string>("姓名", ref f姓名, value); }
        }
        int f年;
        [WatchMember]
        public int 年
        {
            get { return f年; }
            set { SetPropertyValue<int>("年", ref f年, value); }
        }
        int f月;
        [WatchMember]
        public int 月
        {
            get { return f月; }
            set { SetPropertyValue<int>("月", ref f月, value); }
        }
        string f期间;
        [WatchMember]
        public string 期间
        {
            get { return f期间; }
            set { SetPropertyValue<string>("期间", ref f期间, value); }
        }
        decimal f上月剩余金额;
        [WatchMember]
        public decimal 上月剩余金额
        {
            get { return f上月剩余金额; }
            set { SetPropertyValue<decimal>("上月剩余金额", ref f上月剩余金额, value); }
        }
        decimal f上年剩余金额;
        [WatchMember]
        public decimal 上年剩余金额
        {
            get { return f上年剩余金额; }
            set { SetPropertyValue<decimal>("上年剩余金额", ref f上年剩余金额, value); }
        }
        decimal f实际报账金额;
        [WatchMember]
        public decimal 实际报账金额
        {
            get { return f实际报账金额; }
            set { SetPropertyValue<decimal>("实际报账金额", ref f实际报账金额, value); }
        }        
        string f创建人;
        [Size(20)]
        public string 创建人
        {
            get { return f创建人; }
            set { SetPropertyValue<string>("创建人", ref f创建人, value); }
        }
        DateTime f创建时间;
        public DateTime 创建时间
        {
            get { return f创建时间; }
            set { SetPropertyValue<DateTime>("创建时间", ref f创建时间, value); }
        }
    }

}
