//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"薪酬结构_录入")]
    public partial class SalaryStructureEntry : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f员工编号;
        [Size(20)]
        [WatchMember]
        public string 员工编号
        {
            get { return f员工编号; }
            set { SetPropertyValue<string>("员工编号", ref f员工编号, value); }
        }
        DateTime f开始执行日期;
        [WatchMember]
        public DateTime 开始执行日期
        {
            get { return f开始执行日期; }
            set { SetPropertyValue<DateTime>("开始执行日期", ref f开始执行日期, value); }
        }
        string f类型;
        [Size(10)]
        [WatchMember]
        public string 类型
        {
            get { return f类型; }
            set { SetPropertyValue<string>("类型", ref f类型, value); }
        }
        decimal f年薪_12个月;
        [WatchMember]
        public decimal 年薪_12个月
        {
            get { return f年薪_12个月; }
            set { SetPropertyValue<decimal>("年薪_12个月", ref f年薪_12个月, value); }
        }
        decimal f年薪_奖励;
        [WatchMember]
        public decimal 年薪_奖励
        {
            get { return f年薪_奖励; }
            set { SetPropertyValue<decimal>("年薪_奖励", ref f年薪_奖励, value); }
        }
        decimal f年薪_绩效工资;
        [WatchMember]
        public decimal 年薪_绩效工资
        {
            get { return f年薪_绩效工资; }
            set { SetPropertyValue<decimal>("年薪_绩效工资", ref f年薪_绩效工资, value); }
        }
        decimal f年薪_合计;
        [WatchMember]
        public decimal 年薪_合计
        {
            get { return f年薪_合计; }
            set { SetPropertyValue<decimal>("年薪_合计", ref f年薪_合计, value); }
        }
        decimal f月薪项目_月工资;
        [WatchMember]
        public decimal 月薪项目_月工资
        {
            get { return f月薪项目_月工资; }
            set { SetPropertyValue<decimal>("月薪项目_月工资", ref f月薪项目_月工资, value); }
        }
        decimal f月薪项目_年休假;
        [WatchMember]
        public decimal 月薪项目_年休假
        {
            get { return f月薪项目_年休假; }
            set { SetPropertyValue<decimal>("月薪项目_年休假", ref f月薪项目_年休假, value); }
        }
        decimal f月薪项目_满勤奖;
        [WatchMember]
        public decimal 月薪项目_满勤奖
        {
            get { return f月薪项目_满勤奖; }
            set { SetPropertyValue<decimal>("月薪项目_满勤奖", ref f月薪项目_满勤奖, value); }
        }
        decimal f月薪项目_交通餐饮补贴;
        [WatchMember]
        public decimal 月薪项目_交通餐饮补贴
        {
            get { return f月薪项目_交通餐饮补贴; }
            set { SetPropertyValue<decimal>("月薪项目_交通餐饮补贴", ref f月薪项目_交通餐饮补贴, value); }
        }
        decimal f月薪项目_小计;
        [WatchMember]
        public decimal 月薪项目_小计
        {
            get { return f月薪项目_小计; }
            set { SetPropertyValue<decimal>("月薪项目_小计", ref f月薪项目_小计, value); }
        }
        decimal f月薪项目_减项_绩效工资;
        [WatchMember]
        public decimal 月薪项目_减项_绩效工资
        {
            get { return f月薪项目_减项_绩效工资; }
            set { SetPropertyValue<decimal>("月薪项目_减项_绩效工资", ref f月薪项目_减项_绩效工资, value); }
        }
        string f录入人;
        [Size(20)]
        public string 录入人
        {
            get { return f录入人; }
            set { SetPropertyValue<string>("录入人", ref f录入人, value); }
        }
        DateTime f录入时间;
        public DateTime 录入时间
        {
            get { return f录入时间; }
            set { SetPropertyValue<DateTime>("录入时间", ref f录入时间, value); }
        }
        bool f是验证录入;
        public bool 是验证录入
        {
            get { return f是验证录入; }
            set { SetPropertyValue<bool>("是验证录入", ref f是验证录入, value); }
        }
        DateTime f生效时间;
        public DateTime 生效时间
        {
            get { return f生效时间; }
            set { SetPropertyValue<DateTime>("生效时间", ref f生效时间, value); }
        }
    }

}
