//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"薪酬结构_契约津贴")]
    public partial class ContractAllowance : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f员工编号;
        [Size(20)]
        [WatchMember]
        public string 员工编号
        {
            get { return f员工编号; }
            set { SetPropertyValue<string>("员工编号", ref f员工编号, value); }
        }
        DateTime f开始时间;
        [WatchMember]
        public DateTime 开始时间
        {
            get { return f开始时间; }
            set { SetPropertyValue<DateTime>("开始时间", ref f开始时间, value); }
        }
        DateTime f结束时间;
        [WatchMember]
        public DateTime 结束时间
        {
            get { return f结束时间; }
            set { SetPropertyValue<DateTime>("结束时间", ref f结束时间, value); }
        }
        int f约定年限;
        [WatchMember]
        public int 约定年限
        {
            get { return f约定年限; }
            set { SetPropertyValue<int>("约定年限", ref f约定年限, value); }
        }
        decimal f月津贴额度;
        [WatchMember]
        public decimal 月津贴额度
        {
            get { return f月津贴额度; }
            set { SetPropertyValue<decimal>("月津贴额度", ref f月津贴额度, value); }
        }
        decimal f总额度;
        [WatchMember]
        public decimal 总额度
        {
            get { return f总额度; }
            set { SetPropertyValue<decimal>("总额度", ref f总额度, value); }
        }
        string f创建人;
        [Size(20)]
        public string 创建人
        {
            get { return f创建人; }
            set { SetPropertyValue<string>("创建人", ref f创建人, value); }
        }
        DateTime f创建时间;
        public DateTime 创建时间
        {
            get { return f创建时间; }
            set { SetPropertyValue<DateTime>("创建时间", ref f创建时间, value); }
        }
    }

}
