//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"绩效考核结果")]
    public partial class KpiItem : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f员工编号;
        [Size(20)]
        public string 员工编号
        {
            get { return f员工编号; }
            set { SetPropertyValue<string>("员工编号", ref f员工编号, value); }
        }
        int f月;
        public int 月
        {
            get { return f月; }
            set { SetPropertyValue<int>("月", ref f月, value); }
        }
        int f年;
        public int 年
        {
            get { return f年; }
            set { SetPropertyValue<int>("年", ref f年, value); }
        }
        int f岗位序号;
        public int 岗位序号
        {
            get { return f岗位序号; }
            set { SetPropertyValue<int>("岗位序号", ref f岗位序号, value); }
        }
        string f职级代码;
        [Size(10)]
        public string 职级代码
        {
            get { return f职级代码; }
            set { SetPropertyValue<string>("职级代码", ref f职级代码, value); }
        }
        string f职位编号;
        [Size(10)]
        public string 职位编号
        {
            get { return f职位编号; }
            set { SetPropertyValue<string>("职位编号", ref f职位编号, value); }
        }
        DateTime f生效日期;
        public DateTime 生效日期
        {
            get { return f生效日期; }
            set { SetPropertyValue<DateTime>("生效日期", ref f生效日期, value); }
        }
        string f考核项目名称;
        [Size(50)]
        public string 考核项目名称
        {
            get { return f考核项目名称; }
            set { SetPropertyValue<string>("考核项目名称", ref f考核项目名称, value); }
        }
        decimal f考核基准工资;
        public decimal 考核基准工资
        {
            get { return f考核基准工资; }
            set { SetPropertyValue<decimal>("考核基准工资", ref f考核基准工资, value); }
        }
        double f个人挂钩比例;
        public double 个人挂钩比例
        {
            get { return f个人挂钩比例; }
            set { SetPropertyValue<double>("个人挂钩比例", ref f个人挂钩比例, value); }
        }
        double f公司奖励比例;
        public double 公司奖励比例
        {
            get { return f公司奖励比例; }
            set { SetPropertyValue<double>("公司奖励比例", ref f公司奖励比例, value); }
        }
        decimal f个人绩效标准;
        public decimal 个人绩效标准
        {
            get { return f个人绩效标准; }
            set { SetPropertyValue<decimal>("个人绩效标准", ref f个人绩效标准, value); }
        }
        decimal f公司奖励标准;
        public decimal 公司奖励标准
        {
            get { return f公司奖励标准; }
            set { SetPropertyValue<decimal>("公司奖励标准", ref f公司奖励标准, value); }
        }
        decimal f个人绩效实得;
        public decimal 个人绩效实得
        {
            get { return f个人绩效实得; }
            set { SetPropertyValue<decimal>("个人绩效实得", ref f个人绩效实得, value); }
        }
        decimal f公司奖励实得;
        public decimal 公司奖励实得
        {
            get { return f公司奖励实得; }
            set { SetPropertyValue<decimal>("公司奖励实得", ref f公司奖励实得, value); }
        }
        int f原标识;
        public int 原标识
        {
            get { return f原标识; }
            set { SetPropertyValue<int>("原标识", ref f原标识, value); }
        }
        string f创建人;
        [Size(20)]
        public string 创建人
        {
            get { return f创建人; }
            set { SetPropertyValue<string>("创建人", ref f创建人, value); }
        }
        DateTime f创建时间;
        public DateTime 创建时间
        {
            get { return f创建时间; }
            set { SetPropertyValue<DateTime>("创建时间", ref f创建时间, value); }
        }
        DateTime f上次同步时间;
        public DateTime 上次同步时间
        {
            get { return f上次同步时间; }
            set { SetPropertyValue<DateTime>("上次同步时间", ref f上次同步时间, value); }
        }
    }

}
