//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"工资抽查记录")]
    public partial class PayCheckRecord : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f薪资组;
        [Size(20)]
        public string 薪资组
        {
            get { return f薪资组; }
            set { SetPropertyValue<string>("薪资组", ref f薪资组, value); }
        }
        string f日历组;
        [Size(20)]
        public string 日历组
        {
            get { return f日历组; }
            set { SetPropertyValue<string>("日历组", ref f日历组, value); }
        }
        Guid f工资记录标识;
        public Guid 工资记录标识
        {
            get { return f工资记录标识; }
            set { SetPropertyValue<Guid>("工资记录标识", ref f工资记录标识, value); }
        }
        DateTime f抽取时间;
        public DateTime 抽取时间
        {
            get { return f抽取时间; }
            set { SetPropertyValue<DateTime>("抽取时间", ref f抽取时间, value); }
        }
        string f审核人;
        [Size(20)]
        public string 审核人
        {
            get { return f审核人; }
            set { SetPropertyValue<string>("审核人", ref f审核人, value); }
        }
        DateTime f审核确认时间;
        public DateTime 审核确认时间
        {
            get { return f审核确认时间; }
            set { SetPropertyValue<DateTime>("审核确认时间", ref f审核确认时间, value); }
        }
    }

}
