//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"薪酬执行明细")]
    public partial class MonthlySalary : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f员工编号;
        [Size(20)]
        [WatchMember]
        public string 员工编号
        {
            get { return f员工编号; }
            set { SetPropertyValue<string>("员工编号", ref f员工编号, value); }
        }
        int f期号;
        [WatchMember]
        public int 期号
        {
            get { return f期号; }
            set { SetPropertyValue<int>("期号", ref f期号, value); }
        }
        string f薪酬体系;
        [WatchMember]
        public string 薪酬体系
        {
            get { return f薪酬体系; }
            set { SetPropertyValue<string>("薪酬体系", ref f薪酬体系, value); }
        }
        string f职等;
        [WatchMember]
        public string 职等
        {
            get { return f职等; }
            set { SetPropertyValue<string>("职等", ref f职等, value); }
        }
        string f评定_职级;
        [Size(20)]
        [WatchMember]
        public string 评定_职级
        {
            get { return f评定_职级; }
            set { SetPropertyValue<string>("评定_职级", ref f评定_职级, value); }
        }
        int f评定_月薪;
        [WatchMember]
        public int 评定_月薪
        {
            get { return f评定_月薪; }
            set { SetPropertyValue<int>("评定_月薪", ref f评定_月薪, value); }
        }
        string f执行_职级;
        [Size(20)]
        [WatchMember]
        public string 执行_职级
        {
            get { return f执行_职级; }
            set { SetPropertyValue<string>("执行_职级", ref f执行_职级, value); }
        }
        int f执行_月薪;
        [WatchMember]
        public int 执行_月薪
        {
            get { return f执行_月薪; }
            set { SetPropertyValue<int>("执行_月薪", ref f执行_月薪, value); }
        }
        string f执行_月薪类型;
        [Size(20)]
        [WatchMember]
        public string 执行_月薪类型
        {
            get { return f执行_月薪类型; }
            set { SetPropertyValue<string>("执行_月薪类型", ref f执行_月薪类型, value); }
        }
        DateTime f开始执行日期;
        [WatchMember]
        public DateTime 开始执行日期
        {
            get { return f开始执行日期; }
            set { SetPropertyValue<DateTime>("开始执行日期", ref f开始执行日期, value); }
        }
        DateTime f截止日期;
        [WatchMember]
        public DateTime 截止日期
        {
            get { return f截止日期; }
            set { SetPropertyValue<DateTime>("截止日期", ref f截止日期, value); }
        }
        string f调整类型;
        [WatchMember]
        public string 调整类型
        {
            get { return f调整类型; }
            set { SetPropertyValue<string>("调整类型", ref f调整类型, value); }
        }
        string f群组;
        [WatchMember]
        public string 群组
        {
            get { return f群组; }
            set { SetPropertyValue<string>("群组", ref f群组, value); }
        }
        int f序号;
        [WatchMember]
        public int 序号
        {
            get { return f序号; }
            set { SetPropertyValue<int>("序号", ref f序号, value); }
        }
    }

}
