//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"会员_部门")]
    public partial class MemberDept : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f员工编号;
        [Size(20)]
        [WatchMember]
        public string 员工编号
        {
            get { return f员工编号; }
            set { SetPropertyValue<string>("员工编号", ref f员工编号, value); }
        }
        string f所属公司编号;
        [Size(50)]
        [WatchMember]
        public string 所属公司编号
        {
            get { return f所属公司编号; }
            set { SetPropertyValue<string>("所属公司编号", ref f所属公司编号, value); }
        }
        string f所属部门编号;
        [Size(50)]
        [WatchMember]
        public string 所属部门编号
        {
            get { return f所属部门编号; }
            set { SetPropertyValue<string>("所属部门编号", ref f所属部门编号, value); }
        }
        string f职务等级代码;
        [Size(50)]
        [WatchMember]
        public string 职务等级代码
        {
            get { return f职务等级代码; }
            set { SetPropertyValue<string>("职务等级代码", ref f职务等级代码, value); }
        }
        string f可查公司名称;
        [Size(50)]
        [WatchMember]
        public string 可查公司名称
        {
            get { return f可查公司名称; }
            set { SetPropertyValue<string>("可查公司名称", ref f可查公司名称, value); }
        }
        string f可查部门编号;
        [Size(50)]
        [WatchMember]
        public string 可查部门编号
        {
            get { return f可查部门编号; }
            set { SetPropertyValue<string>("可查部门编号", ref f可查部门编号, value); }
        }
    }

}
