//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"会员_等级")]
    public partial class MemberGrade : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f员工编号;
        [Size(20)]
        public string 员工编号
        {
            get { return f员工编号; }
            set { SetPropertyValue<string>("员工编号", ref f员工编号, value); }
        }
        string f公司名称;
        [Size(10)]
        public string 公司名称
        {
            get { return f公司名称; }
            set { SetPropertyValue<string>("公司名称", ref f公司名称, value); }
        }
        string f工资职等;
        [Size(10)]
        public string 工资职等
        {
            get { return f工资职等; }
            set { SetPropertyValue<string>("工资职等", ref f工资职等, value); }
        }
    }

}
