//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"会员")]
    public partial class Member : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f员工编号;
        [Size(20)]
        public string 员工编号
        {
            get { return f员工编号; }
            set { SetPropertyValue<string>("员工编号", ref f员工编号, value); }
        }
        string f姓名;
        [Size(10)]
        public string 姓名
        {
            get { return f姓名; }
            set { SetPropertyValue<string>("姓名", ref f姓名, value); }
        }
        string f密码;
        public string 密码
        {
            get { return f密码; }
            set { SetPropertyValue<string>("密码", ref f密码, value); }
        }
        string f盐;
        [Size(10)]
        public string 盐
        {
            get { return f盐; }
            set { SetPropertyValue<string>("盐", ref f盐, value); }
        }
        string f身份证号码;
        [Size(20)]
        public string 身份证号码
        {
            get { return f身份证号码; }
            set { SetPropertyValue<string>("身份证号码", ref f身份证号码, value); }
        }
        string f用户类型;
        [Size(20)]
        public string 用户类型
        {
            get { return f用户类型; }
            set { SetPropertyValue<string>("用户类型", ref f用户类型, value); }
        }
        bool f有异动;
        public bool 有异动
        {
            get { return f有异动; }
            set { SetPropertyValue<bool>("有异动", ref f有异动, value); }
        }
        string f公司编号;
        [Size(50)]
        public string 公司编号
        {
            get { return f公司编号; }
            set { SetPropertyValue<string>("公司编号", ref f公司编号, value); }
        }
        string f部门编号;
        [Size(50)]
        public string 部门编号
        {
            get { return f部门编号; }
            set { SetPropertyValue<string>("部门编号", ref f部门编号, value); }
        }
        string f职务等级;
        [Size(50)]
        public string 职务等级
        {
            get { return f职务等级; }
            set { SetPropertyValue<string>("职务等级", ref f职务等级, value); }
        }
        DateTime f创建时间;
        public DateTime 创建时间
        {
            get { return f创建时间; }
            set { SetPropertyValue<DateTime>("创建时间", ref f创建时间, value); }
        }
        DateTime f最后登录时间;
        public DateTime 最后登录时间
        {
            get { return f最后登录时间; }
            set { SetPropertyValue<DateTime>("最后登录时间", ref f最后登录时间, value); }
        }
    }

}
