//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"管培生_工资标准_录入")]
    public partial class ManagementTraineePayStandardInput : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        int f序号;
        [WatchMember]
        public int 序号
        {
            get { return f序号; }
            set { SetPropertyValue<int>("序号", ref f序号, value); }
        }
        string f员工编号;
        [Size(20)]
        [WatchMember]

        public string 员工编号
        {
            get { return f员工编号; }
            set { SetPropertyValue<string>("员工编号", ref f员工编号, value); }
        }
        string f姓名;
        [Size(20)]
        [WatchMember]

        public string 姓名
        {
            get { return f姓名; }
            set { SetPropertyValue<string>("姓名", ref f姓名, value); }
        }
        int f提资序数;
        [WatchMember]
        public int 提资序数
        {
            get { return f提资序数; }
            set { SetPropertyValue<int>("提资序数", ref f提资序数, value); }
        }
        int f年份;
        [WatchMember]
        public int 年份
        {
            get { return f年份; }
            set { SetPropertyValue<int>("年份", ref f年份, value); }
        }
        int f季度;
        [WatchMember]
        public int 季度
        {
            get { return f季度; }
            set { SetPropertyValue<int>("季度", ref f季度, value); }
        }
        decimal f增幅;
        public decimal 增幅
        {
            get { return f增幅; }
            set { SetPropertyValue<decimal>("增幅", ref f增幅, value); }
        }
        decimal f年薪;
        [WatchMember]
        public decimal 年薪
        {
            get { return f年薪; }
            set { SetPropertyValue<decimal>("年薪", ref f年薪, value); }
        }
        int f月薪;
        public int 月薪
        {
            get { return f月薪; }
            set { SetPropertyValue<int>("月薪", ref f月薪, value); }
        }
        string f备注;
        [Size(50)]
        [WatchMember]
        public string 备注
        {
            get { return f备注; }
            set { SetPropertyValue<string>("备注", ref f备注, value); }
        }
        DateTime f开始执行时间;
        public DateTime 开始执行时间
        {
            get { return f开始执行时间; }
            set { SetPropertyValue<DateTime>("开始执行时间", ref f开始执行时间, value); }
        }
        string f录入人;
        [Size(20)]
        public string 录入人
        {
            get { return f录入人; }
            set { SetPropertyValue<string>("录入人", ref f录入人, value); }
        }
        DateTime f录入时间;
        public DateTime 录入时间
        {
            get { return f录入时间; }
            set { SetPropertyValue<DateTime>("录入时间", ref f录入时间, value); }
        }
        bool f是验证录入;
        public bool 是验证录入
        {
            get { return f是验证录入; }
            set { SetPropertyValue<bool>("是验证录入", ref f是验证录入, value); }
        }
        DateTime f生效时间;
        public DateTime 生效时间
        {
            get { return f生效时间; }
            set { SetPropertyValue<DateTime>("生效时间", ref f生效时间, value); }
        }
        public ManagementTraineePayStandardInput() : base(MyHelper.XpoSession) { }
        public ManagementTraineePayStandardInput(Session session) : base(session) { }
    }

}
