//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{
    [Persistent(@"部门体系")]
    public partial class DeptSystem : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f部门编号;
        [Size(20)]
        public string 部门编号
        {
            get { return f部门编号; }
            set { SetPropertyValue<string>("部门编号", ref f部门编号, value); }
        }        
        string f部门名称;
        [Size(50)]
        public string 部门名称
        {
            get { return f部门名称; }
            set { SetPropertyValue<string>("部门名称", ref f部门名称, value); }
        }
        string f体系;
        [Size(50)]
        public string 体系
        {
            get { return f体系; }
            set { SetPropertyValue<string>("体系", ref f体系, value); }
        }
        string f本部;
        [Size(50)]
        public string 本部
        {
            get { return f本部; }
            set { SetPropertyValue<string>("本部", ref f本部, value); }
        }     
        string f录入人;
        [Size(20)]
        public string 录入人
        {
            get { return f录入人; }
            set { SetPropertyValue<string>("录入人", ref f录入人, value); }
        }
        DateTime f录入时间;
        public DateTime 录入时间
        {
            get { return f录入时间; }
            set { SetPropertyValue<DateTime>("录入时间", ref f录入时间, value); }
        }
    }

}
