//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"管培生_综合能力评定")]
    public partial class ManagementTraineeAbility : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f员工编号;
        [Size(20)]
        public string 员工编号
        {
            get { return f员工编号; }
            set { SetPropertyValue<string>("员工编号", ref f员工编号, value); }
        }
        string f姓名;
        [Size(20)]
        public string 姓名
        {
            get { return f姓名; }
            set { SetPropertyValue<string>("姓名", ref f姓名, value); }
        }
        int f序号;
        public int 序号
        {
            get { return f序号; }
            set { SetPropertyValue<int>("序号", ref f序号, value); }
        }
        string f届别;
        [Size(10)]
        public string 届别
        {
            get { return f届别; }
            set { SetPropertyValue<string>("届别", ref f届别, value); }
        }
        string f岗位级别;
        [Size(10)]
        public string 岗位级别
        {
            get { return f岗位级别; }
            set { SetPropertyValue<string>("岗位级别", ref f岗位级别, value); }
        }
        int f年度;
        public int 年度
        {
            get { return f年度; }
            set { SetPropertyValue<int>("年度", ref f年度, value); }
        }
        string f能力级别;
        [Size(10)]
        public string 能力级别
        {
            get { return f能力级别; }
            set { SetPropertyValue<string>("能力级别", ref f能力级别, value); }
        }        
        DateTime f创建时间;
        public DateTime 创建时间
        {
            get { return f创建时间; }
            set { SetPropertyValue<DateTime>("创建时间", ref f创建时间, value); }
        }
        DateTime f更新时间;
        public DateTime 更新时间
        {
            get { return f更新时间; }
            set { SetPropertyValue<DateTime>("更新时间", ref f更新时间, value); }
        }
        public ManagementTraineeAbility() : base(MyHelper.XpoSession) { }
        public ManagementTraineeAbility(Session session) : base(session) { }
    }

}
