//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"管培生_基本信息")]
    public partial class ManagementTraineeInfo : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f员工编号;
        [Size(20)]
        public string 员工编号
        {
            get { return f员工编号; }
            set { SetPropertyValue<string>("员工编号", ref f员工编号, value); }
        }
        string f姓名;
        [Size(20)]
        public string 姓名
        {
            get { return f姓名; }
            set { SetPropertyValue<string>("姓名", ref f姓名, value); }
        }
        string f学历;
        [Size(20)]
        public string 学历
        {
            get { return f学历; }
            set { SetPropertyValue<string>("学历", ref f学历, value); }
        }
        string f学历备注;
        [Size(20)]
        public string 学历备注
        {
            get { return f学历备注; }
            set { SetPropertyValue<string>("学历备注", ref f学历备注, value); }
        }
        string f专业名称;
        [Size(20)]
        public string 专业名称
        {
            get { return f专业名称; }
            set { SetPropertyValue<string>("专业名称", ref f专业名称, value); }
        }
        string f专业属性;
        [Size(10)]
        public string 专业属性
        {
            get { return f专业属性; }
            set { SetPropertyValue<string>("专业属性", ref f专业属性, value); }
        }
        string f岗位级别;
        [Size(10)]
        public string 岗位级别
        {
            get { return f岗位级别; }
            set { SetPropertyValue<string>("岗位级别", ref f岗位级别, value); }
        }
        string f岗位类型;
        [Size(20)]
        public string 岗位类型
        {
            get { return f岗位类型; }
            set { SetPropertyValue<string>("岗位类型", ref f岗位类型, value); }
        }
        DateTime f入职时间;
        public DateTime 入职时间
        {
            get { return f入职时间; }
            set { SetPropertyValue<DateTime>("入职时间", ref f入职时间, value); }
        }
        string f届别;
        [Size(10)]
        public string 届别
        {
            get { return f届别; }
            set { SetPropertyValue<string>("届别", ref f届别, value); }
        }
        decimal f年薪;
        public decimal 年薪
        {
            get { return f年薪; }
            set { SetPropertyValue<decimal>("年薪", ref f年薪, value); }
        }
        string f备注;
        [Size(50)]
        public string 备注
        {
            get { return f备注; }
            set { SetPropertyValue<string>("备注", ref f备注, value); }
        }
        DateTime f截止日期;
        public DateTime 截止日期
        {
            get { return f截止日期; }
            set { SetPropertyValue<DateTime>("截止日期", ref f截止日期, value); }
        }
        DateTime f更新时间;
        public DateTime 更新时间
        {
            get { return f更新时间; }
            set { SetPropertyValue<DateTime>("更新时间", ref f更新时间, value); }
        }
        public ManagementTraineeInfo() : base(MyHelper.XpoSession) { }
        public ManagementTraineeInfo(Session session) : base(session) { }
    }

}
