//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"管培生_综合能力评定_录入")]
    public partial class ManagementTraineeAbilityInput : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f员工编号;
        [Size(20)]
        [WatchMember]
        public string 员工编号
        {
            get { return f员工编号; }
            set { SetPropertyValue<string>("员工编号", ref f员工编号, value); }
        }
        string f姓名;
        [Size(20)]
        [WatchMember]
        public string 姓名
        {
            get { return f姓名; }
            set { SetPropertyValue<string>("姓名", ref f姓名, value); }
        }
        int f序号;
        public int 序号
        {
            get { return f序号; }
            set { SetPropertyValue<int>("序号", ref f序号, value); }
        }
        string f届别;
        [Size(10)]
        [WatchMember]
        public string 届别
        {
            get { return f届别; }
            set { SetPropertyValue<string>("届别", ref f届别, value); }
        }
        string f岗位级别;
        [Size(10)]
        [WatchMember]
        public string 岗位级别
        {
            get { return f岗位级别; }
            set { SetPropertyValue<string>("岗位级别", ref f岗位级别, value); }
        }
        int f年度;
        [WatchMember]
        public int 年度
        {
            get { return f年度; }
            set { SetPropertyValue<int>("年度", ref f年度, value); }
        }
        string f能力级别;
        [Size(10)]
        [WatchMember]
        public string 能力级别
        {
            get { return f能力级别; }
            set { SetPropertyValue<string>("能力级别", ref f能力级别, value); }
        }
        string f录入人;
        [Size(20)]
        public string 录入人
        {
            get { return f录入人; }
            set { SetPropertyValue<string>("录入人", ref f录入人, value); }
        }
        DateTime f录入时间;
        public DateTime 录入时间
        {
            get { return f录入时间; }
            set { SetPropertyValue<DateTime>("录入时间", ref f录入时间, value); }
        }
        bool f是验证录入;
        public bool 是验证录入
        {
            get { return f是验证录入; }
            set { SetPropertyValue<bool>("是验证录入", ref f是验证录入, value); }
        }
        DateTime f生效时间;
        public DateTime 生效时间
        {
            get { return f生效时间; }
            set { SetPropertyValue<DateTime>("生效时间", ref f生效时间, value); }
        }
        public ManagementTraineeAbilityInput() : base(MyHelper.XpoSession) { }
        public ManagementTraineeAbilityInput(Session session) : base(session) { }
    }

}
