//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"管培生_工资标准")]
    public partial class ManagementTraineePayStandard : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f员工编号;
        [Size(20)]
        public string 员工编号
        {
            get { return f员工编号; }
            set { SetPropertyValue<string>("员工编号", ref f员工编号, value); }
        }
        string f姓名;
        [Size(20)]
        public string 姓名
        {
            get { return f姓名; }
            set { SetPropertyValue<string>("姓名", ref f姓名, value); }
        }
        int f提资序数;
        public int 提资序数
        {
            get { return f提资序数; }
            set { SetPropertyValue<int>("提资序数", ref f提资序数, value); }
        }
        int f年份;
        public int 年份
        {
            get { return f年份; }
            set { SetPropertyValue<int>("年份", ref f年份, value); }
        }
        int f季度;
        public int 季度
        {
            get { return f季度; }
            set { SetPropertyValue<int>("季度", ref f季度, value); }
        }
        decimal f增幅;
        public decimal 增幅
        {
            get { return f增幅; }
            set { SetPropertyValue<decimal>("增幅", ref f增幅, value); }
        }
        decimal f年薪;
        public decimal 年薪
        {
            get { return f年薪; }
            set { SetPropertyValue<decimal>("年薪", ref f年薪, value); }
        }
        int f月薪;
        public int 月薪
        {
            get { return f月薪; }
            set { SetPropertyValue<int>("月薪", ref f月薪, value); }
        }
        string f备注;
        [Size(50)]
        public string 备注
        {
            get { return f备注; }
            set { SetPropertyValue<string>("备注", ref f备注, value); }
        }
        DateTime f开始执行时间;
        public DateTime 开始执行时间
        {
            get { return f开始执行时间; }
            set { SetPropertyValue<DateTime>("开始执行时间", ref f开始执行时间, value); }
        }
        string f创建人;
        [Size(20)]
        public string 创建人
        {
            get { return f创建人; }
            set { SetPropertyValue<string>("创建人", ref f创建人, value); }
        }
        DateTime f创建时间;
        public DateTime 创建时间
        {
            get { return f创建时间; }
            set { SetPropertyValue<DateTime>("创建时间", ref f创建时间, value); }
        }
        public ManagementTraineePayStandard() : base(MyHelper.XpoSession) { }
        public ManagementTraineePayStandard(Session session) : base(session) { }
    }

}
