//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"职级工资标准")]
    public partial class RankSalaryStandard : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f薪酬体系;
        public string 薪酬体系
        {
            get { return f薪酬体系; }
            set { SetPropertyValue<string>("薪酬体系", ref f薪酬体系, value); }
        }
        string f职等;
        public string 职等
        {
            get { return f职等; }
            set { SetPropertyValue<string>("职等", ref f职等, value); }
        }
        string f职级;
        public string 职级
        {
            get { return f职级; }
            set { SetPropertyValue<string>("职级", ref f职级, value); }
        }
        int f期号;
        public int 期号
        {
            get { return f期号; }
            set { SetPropertyValue<int>("期号", ref f期号, value); }
        }
        int f月薪;
        public int 月薪
        {
            get { return f月薪; }
            set { SetPropertyValue<int>("月薪", ref f月薪, value); }
        }
        DateTime f开始执行日期;
        public DateTime 开始执行日期
        {
            get { return f开始执行日期; }
            set { SetPropertyValue<DateTime>("开始执行日期", ref f开始执行日期, value); }
        }
        int f序号;
        public int 序号
        {
            get { return f序号; }
            set { SetPropertyValue<int>("序号", ref f序号, value); }
        }
    }

}
