//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"薪酬结构_工资借款_发放明细_录入")]
    public partial class MonthlyWageLoanItemEntry : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f员工编号;
        [Size(20)]
        [WatchMember]
        public string 员工编号
        {
            get { return f员工编号; }
            set { SetPropertyValue<string>("员工编号", ref f员工编号, value); }
        }
        string f姓名;
        [Size(10)]
        [WatchMember]
        public string 姓名
        {
            get { return f姓名; }
            set { SetPropertyValue<string>("姓名", ref f姓名, value); }
        }
        string f期间;
        [Size(10)]
        [WatchMember]
        public string 期间
        {
            get { return f期间; }
            set { SetPropertyValue<string>("期间", ref f期间, value); }
        }
        int f年;
        [WatchMember]
        public int 年
        {
            get { return f年; }
            set { SetPropertyValue<int>("年", ref f年, value); }
        }
        int f月;
        [WatchMember]
        public int 月
        {
            get { return f月; }
            set { SetPropertyValue<int>("月", ref f月, value); }
        }
        decimal f约定税率;
        [WatchMember]
        public decimal 约定税率
        {
            get { return f约定税率; }
            set { SetPropertyValue<decimal>("约定税率", ref f约定税率, value); }
        }
        decimal f月借款标准;
        [WatchMember]
        public decimal 月借款标准
        {
            get { return f月借款标准; }
            set { SetPropertyValue<decimal>("月借款标准", ref f月借款标准, value); }
        }
        decimal f应出勤天数;
        [WatchMember]
        public decimal 应出勤天数
        {
            get { return f应出勤天数; }
            set { SetPropertyValue<decimal>("应出勤天数", ref f应出勤天数, value); }
        }
        decimal f实际出勤天数;
        [WatchMember]
        public decimal 实际出勤天数
        {
            get { return f实际出勤天数; }
            set { SetPropertyValue<decimal>("实际出勤天数", ref f实际出勤天数, value); }
        }
        decimal f实际借款金额;
        [WatchMember]
        public decimal 实际借款金额
        {
            get { return f实际借款金额; }
            set { SetPropertyValue<decimal>("实际借款金额", ref f实际借款金额, value); }
        }
        decimal f代缴个税;
        [WatchMember]
        public decimal 代缴个税
        {
            get { return f代缴个税; }
            set { SetPropertyValue<decimal>("代缴个税", ref f代缴个税, value); }
        }
        decimal f税后实发金额;
        [WatchMember]
        public decimal 税后实发金额
        {
            get { return f税后实发金额; }
            set { SetPropertyValue<decimal>("税后实发金额", ref f税后实发金额, value); }
        }
        string f录入人;
        [Size(20)]
        public string 录入人
        {
            get { return f录入人; }
            set { SetPropertyValue<string>("录入人", ref f录入人, value); }
        }
        DateTime f录入时间;
        public DateTime 录入时间
        {
            get { return f录入时间; }
            set { SetPropertyValue<DateTime>("录入时间", ref f录入时间, value); }
        }
        bool f是验证录入;
        public bool 是验证录入
        {
            get { return f是验证录入; }
            set { SetPropertyValue<bool>("是验证录入", ref f是验证录入, value); }
        }
        DateTime f生效时间;
        public DateTime 生效时间
        {
            get { return f生效时间; }
            set { SetPropertyValue<DateTime>("生效时间", ref f生效时间, value); }
        }
    }

}
