//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Hwagain.SalaryCalculation.Components
{

    [Persistent(@"管培生_提资标准")]
    public partial class ManagementTraineePayRiseStandard : XPLiteObject
    {
        Guid f标识;
        [Key(true)]
        public Guid 标识
        {
            get { return f标识; }
            set { SetPropertyValue<Guid>("标识", ref f标识, value); }
        }
        string f届别;
        [Size(10)]
        public string 届别
        {
            get { return f届别; }
            set { SetPropertyValue<string>("届别", ref f届别, value); }
        }
        string f岗位级别;
        [Size(10)]
        public string 岗位级别
        {
            get { return f岗位级别; }
            set { SetPropertyValue<string>("岗位级别", ref f岗位级别, value); }
        }
        string f类别;
        [Size(20)]
        public string 类别
        {
            get { return f类别; }
            set { SetPropertyValue<string>("类别", ref f类别, value); }
        }
        string f能力级别;
        [Size(10)]
        public string 能力级别
        {
            get { return f能力级别; }
            set { SetPropertyValue<string>("能力级别", ref f能力级别, value); }
        }
        int f序号;
        public int 序号
        {
            get { return f序号; }
            set { SetPropertyValue<int>("序号", ref f序号, value); }
        }
        string f提资周期;
        [Size(20)]
        public string 提资周期
        {
            get { return f提资周期; }
            set { SetPropertyValue<string>("提资周期", ref f提资周期, value); }
        }
        int f提资序数;
        public int 提资序数
        {
            get { return f提资序数; }
            set { SetPropertyValue<int>("提资序数", ref f提资序数, value); }
        }
        decimal f增幅;
        public decimal 增幅
        {
            get { return f增幅; }
            set { SetPropertyValue<decimal>("增幅", ref f增幅, value); }
        }
        decimal f年薪;
        public decimal 年薪
        {
            get { return f年薪; }
            set { SetPropertyValue<decimal>("年薪", ref f年薪, value); }
        }
        int f提资方式;
        public int 提资方式
        {
            get { return f提资方式; }
            set { SetPropertyValue<int>("提资方式", ref f提资方式, value); }
        }
        string f创建人;
        [Size(20)]
        public string 创建人
        {
            get { return f创建人; }
            set { SetPropertyValue<string>("创建人", ref f创建人, value); }
        }
        DateTime f创建时间;
        public DateTime 创建时间
        {
            get { return f创建时间; }
            set { SetPropertyValue<DateTime>("创建时间", ref f创建时间, value); }
        }
        public ManagementTraineePayRiseStandard() : base(MyHelper.XpoSession) { }
        public ManagementTraineePayRiseStandard(Session session) : base(session) { }
    }

}
